trigger:
- master
- develop

pr:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
     src/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: |
     tests/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)'

- script: dotnet pack ./src/SafeParallelAsync/SafeParallelAsync.csproj --configuration $(buildConfiguration) --no-build --output %Build_ArtifactStagingDirectory%
  condition: succeeded()
  displayName: Pack

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: SafeParallelAsyncNugetPackage
